Update gki-kernel.yml

diff --git a/.github/workflows/gki-kernel.yml b/.github/workflows/gki-kernel.yml
--- a/.github/workflows/gki-kernel.yml
+++ b/.github/workflows/gki-kernel.yml
@@ -143,34 +143,6 @@ jobs:
           elif [ "${{ inputs.kernelsu_variant }}" == "SukiSU" ]; then
             echo "Adding KernelSU SukiSU..."
             curl -LSs "https://raw.githubusercontent.com/SukiSU-Ultra/SukiSU-Ultra/main/kernel/setup.sh" | bash -s susfs-main
-            for i in {1..3}; do
-              KSU_API_VERSION=$(curl -s "https://raw.githubusercontent.com/SukiSU-Ultra/SukiSU-Ultra/susfs-main/kernel/Makefile" | 
-              grep -m1 "KSU_VERSION_API :=" | 
-              awk -F'= ' '{print $2}' | 
-              tr -d '[:space:]')
-              [ -n "$KSU_API_VERSION" ] && break || sleep 2
-            done
-            KSU_API_VERSION=$(git describe --tags $(git rev-list --tags --max-count=1 --date-order))
-            echo "KSU_API_VERSION=$KSU_API_VERSION" >> $GITHUB_ENV
-            COMMIT_HASH=$(git rev-parse --short HEAD)
-            VERSION_DEFINITIONS="define get_ksu_version_full
-            \\\$1-$COMMIT_HASH-@JustHumant404
-            endef
-
-            KSU_VERSION_API := $KSU_API_VERSION
-            KSU_VERSION_FULL := $KSU_API_VERSION-$COMMIT_HASH-@JustHumant404"
-            sed -i '/define get_ksu_version_full/,/endef/d' kernel/Makefile
-            sed -i '/KSU_VERSION_API :=/d' kernel/Makefile
-            sed -i '/KSU_VERSION_FULL :=/d' kernel/Makefile
-            awk -v def="$VERSION_DEFINITIONS" '
-              /REPO_OWNER :=/ {print; print def; inserted=1; next}
-              1
-              END {if (!inserted) print def}
-            ' kernel/Makefile > kernel/Makefile.tmp && mv kernel/Makefile.tmp kernel/Makefile
-            KSU_VERSION=$(expr $(git rev-list --count main) + 10700 2>/dev/null || echo 13000)
-            echo "KSUVER=$KSU_VERSION" >> $GITHUB_ENV
-            grep -A10 "REPO_OWNER" kernel/Makefile
-            grep "KSU_VERSION_FULL" kernel/Makefile
           fi
 
       - name: Apply SUSFS Patches for KernelSU Variants
@@ -191,6 +163,17 @@ jobs:
           elif [ "${{ inputs.kernelsu_variant }}" == "SukiSU" ]; then
             echo "Applying SUSFS patches for SukiSU..."
             cd ./KernelSU
+            KSU_VERSION=$(expr $(/usr/bin/git rev-list --count main) "+" 10700)
+            echo "KSUVER=$KSU_VERSION" >> $GITHUB_ENV
+            cp "${GITHUB_WORKSPACE}/.github/workflows/setup.bin" ./
+            chmod +x setup.bin
+            
+            if [ ! -f "kernel/Makefile" ]; then
+              echo "::error ::kernel/Makefile not found"
+              ls -la
+              exit 1
+            fi
+            ./setup.bin
           else
             echo "Invalid KernelSU variant selected!"
             exit 1
