Update gki-kernel.yml

diff --git a/.github/workflows/gki-kernel.yml b/.github/workflows/gki-kernel.yml
--- a/.github/workflows/gki-kernel.yml
+++ b/.github/workflows/gki-kernel.yml
@@ -234,11 +234,16 @@ jobs:
           elif [ "${{ inputs.kernelsu_variant }}" == "SukiSU-Ultra" ]; then
             echo "Applying SUSFS patches for SukiSU..."
             cd ./KernelSU
-            # KSU_VERSION=$(expr $(git rev-list --count main 2>/dev/null || echo 13000) + 10700)
-            # echo "KSUVER=$KSU_VERSION" >> $GITHUB_ENV
-            # curl -LSs https://github.com/$GITHUB_REPOSITORY/raw/main/.github/workflows/setup.sh -o setup.sh
-            # chmod +x setup.sh
-            # ./setup.sh
+            KSU_VERSION=$(expr $(git rev-list --count main 2>/dev/null || echo 13000) + 10700)
+            echo "KSUVER=$KSU_VERSION" >> $GITHUB_ENV
+            curl -LSs https://github.com/$GITHUB_REPOSITORY/raw/main/.github/workflows/setup.sh -o setup.sh
+            chmod +x setup.sh
+            if [ ! -f "kernel/Makefile" ]; then
+              echo "❌ kernel/Makefile not found"
+              ls -la
+              exit 1
+            fi
+            ./setup.sh
           else
             echo "Invalid KernelSU variant selected!"
             exit 1
@@ -264,42 +269,53 @@ jobs:
 
       - name: Upgrade LZ4 to v1.10.0
         run: |
-          cd kernel_workspace/common
-          
-          # Delete old files in lz4 library
-          files=(
-            "lib/lz4/lz4_compress.c"
-            "lib/lz4/lz4_decompress.c"
-            "lib/lz4/lz4defs.h"
-            "lib/lz4/lz4hc_compress.c"
-          )
-
-          for file in "${files[@]}"; do
-            if [ -e "$file" ]; then
-              rm -rf "$file"
-              echo "$file Deleted"
-            else
-              echo "$file Does not exist"
-            fi
-          done
-
-          cp -r ../../kernel_patches/zram/lz4/* ./lib/lz4/
-          cp -r ../../kernel_patches/zram/include/linux/* ./include/linux/
-          cp -r ../../kernel_patches/zram/${{ inputs.kernel_version }}/lz4_1.10.0.patch ./
-          patch -p1 -F 3 --fuzz=5 < lz4_1.10.0.patch || true
-
-          # Check if the file exists
-          if [ -f "fs/f2fs/Makefile" ]; then
-            # Check whether the specified line is contained
-            if ! grep -qF "f2fs-\$(CONFIG_F2FS_IOSTAT) += iostat.o" "fs/f2fs/Makefile"; then
-              echo "f2fs-\$(CONFIG_F2FS_IOSTAT) += iostat.o" >> "fs/f2fs/Makefile"
-              echo "Added: f2fs-\$(CONFIG_F2FS_IOSTAT) += iostat.o"
-            else
-              echo "File already contains: f2fs-\$(CONFIG_F2FS_IOSTAT) += iostat.o"
-            fi
-          else
-            echo "File does not exist: fs/f2fs/Makefile"
+          cd kernel_workspace
+          if [ "${{ inputs.use_bbr }}" == "true" ]; then
+            cp ../kernel_patches/zram/001-lz4.patch ./common
+            cp ../kernel_patches/zram/lz4armv8.S ./common/lib
+            cp ../kernel_patches/zram/002-zstd.patch ./common/
           fi
+
+          cd ./common
+          if [ "${{ inputs.use_bbr }}" == "true" ]; then
+            echo "📦 应用lz4+zstd补丁..."
+            git apply -p1 < 001-lz4.patch || true
+            patch -p1 < 002-zstd.patch || true
+          fi
+      #     # Delete old files in lz4 library
+      #     files=(
+      #       "lib/lz4/lz4_compress.c"
+      #       "lib/lz4/lz4_decompress.c"
+      #       "lib/lz4/lz4defs.h"
+      #       "lib/lz4/lz4hc_compress.c"
+      #     )
+
+      #     for file in "${files[@]}"; do
+      #       if [ -e "$file" ]; then
+      #         rm -rf "$file"
+      #         echo "$file Deleted"
+      #       else
+      #         echo "$file Does not exist"
+      #       fi
+      #     done
+
+      #     cp -r ../../kernel_patches/zram/lz4/* ./lib/lz4/
+      #     cp -r ../../kernel_patches/zram/include/linux/* ./include/linux/
+      #     cp -r ../../kernel_patches/zram/${{ inputs.kernel_version }}/lz4_1.10.0.patch ./
+      #     patch -p1 -F 3 --fuzz=5 < lz4_1.10.0.patch || true
+
+      #     # Check if the file exists
+      #     if [ -f "fs/f2fs/Makefile" ]; then
+      #       # Check whether the specified line is contained
+      #       if ! grep -qF "f2fs-\$(CONFIG_F2FS_IOSTAT) += iostat.o" "fs/f2fs/Makefile"; then
+      #         echo "f2fs-\$(CONFIG_F2FS_IOSTAT) += iostat.o" >> "fs/f2fs/Makefile"
+      #         echo "Added: f2fs-\$(CONFIG_F2FS_IOSTAT) += iostat.o"
+      #       else
+      #         echo "File already contains: f2fs-\$(CONFIG_F2FS_IOSTAT) += iostat.o"
+      #       fi
+      #     else
+      #       echo "File does not exist: fs/f2fs/Makefile"
+      #     fi
 
       - name: 🔧 LZ4 v1.10.0 Configuration
         run: |
@@ -319,7 +335,8 @@ jobs:
             # Enable advanced compression support
             echo "CONFIG_CRYPTO_LZ4=y" >> ./common/arch/arm64/configs/gki_defconfig
             echo "CONFIG_CRYPTO_LZ4HC=y" >> ./common/arch/arm64/configs/gki_defconfig
-          
+            echo "CONFIG_CRYPTO_ZSTD=y" >> ./common/arch/arm64/configs/gki_defconfig
+            
             # File system level compression support
             echo "CONFIG_F2FS_FS_COMPRESSION=y" >> ./common/arch/arm64/configs/gki_defconfig
             echo "CONFIG_F2FS_FS_LZ4=y" >> ./common/arch/arm64/configs/gki_defconfig
@@ -379,9 +396,11 @@ jobs:
             echo "CONFIG_TCP_CONG_BBR=y" >> ./common/arch/arm64/configs/gki_defconfig
             echo "CONFIG_NET_SCH_FQ=y" >> ./common/arch/arm64/configs/gki_defconfig
             echo "CONFIG_TCP_CONG_BIC=n" >> ./common/arch/arm64/configs/gki_defconfig
+            echo "CONFIG_TCP_CONG_CUBIC=n" >> ./common/arch/arm64/configs/gki_defconfig
             echo "CONFIG_TCP_CONG_WESTWOOD=n" >> ./common/arch/arm64/configs/gki_defconfig
             echo "CONFIG_TCP_CONG_HTCP=n" >> ./common/arch/arm64/configs/gki_defconfig
             echo "CONFIG_DEFAULT_BBR=y" >> ./common/arch/arm64/configs/gki_defconfig
+            echo "CONFIG_DEFAULT_TCP_CONG=bbr" >> ./common/arch/arm64/configs/gki_defconfig
           fi
           
           # Remove check_defconfig
